import React, { Component } from 'react';

class WordLists extends Component{
    codenamesList = [
        "Hollywood",
        "Well",
        "Foot",
        "New York",
        "Spring",
        "Court",
        "Tube",
        "Point",
        "Tablet",
        "Slip",
        "Date",
        "Drill",
        "Lemon",
        "Bell",
        "Screen",
        "Fair",
        "Torch",
        "State",
        "Match",
        "Iron",
        "Block",
        "France",
        "Australia",
        "Limousine",
        "Stream",
        "Glove",
        "Nurse",
        "Leprechaun",
        "Play",
        "Tooth",
        "Arm",
        "Bermuda",
        "Diamond",
        "Whale",
        "Comic",
        "Mammoth",
        "Green",
        "Pass",
        "Missile",
        "Paste",
        "Drop",
        "Phoenix",
        "Marble",
        "Staff",
        "Figure",
        "Park",
        "Centaur",
        "Shadow",
        "Fish",
        "Cotton",
        "Egypt",
        "Theater",
        "Scale",
        "Fall",
        "Track",
        "Force",
        "Dinosaur",
        "Bill",
        "Mine",
        "Turkey",
        "March",
        "Contract",
        "Bridge",
        "Robin",
        "Line",
        "Plate",
        "Band",
        "Fire",
        "Bank",
        "Boom",
        "Cat",
        "Shot",
        "Suit",
        "Chocolate",
        "Roulette",
        "Mercury",
        "Moon",
        "Net",
        "Lawyer",
        "Satellite",
        "Angel",
        "Spider",
        "Germany",
        "Fork",
        "Pitch",
        "King",
        "Crane",
        "Trip",
        "Dog",
        "Conductor",
        "Part",
        "Bugle",
        "Witch",
        "Ketchup",
        "Press",
        "Spine",
        "Worm",
        "Alps",
        "Bond",
        "Pan",
        "Beijing",
        "Racket",
        "Cross",
        "Seal",
        "Aztec",
        "Maple",
        "Parachute",
        "Hotel",
        "Berry",
        "Soldier",
        "Ray",
        "Post",
        "Greece",
        "Square",
        "Mass",
        "Bat",
        "Wave",
        "Car",
        "Smuggler",
        "England",
        "Crash",
        "Tail",
        "Card",
        "Horn",
        "Capital",
        "Fence",
        "Deck",
        "Buffalo",
        "Microscope",
        "Jet",
        "Duck",
        "Ring",
        "Train",
        "Field",
        "Gold",
        "Tick",
        "Check",
        "Queen",
        "Strike",
        "Kangaroo",
        "Spike",
        "Scientist",
        "Engine",
        "Shakespeare",
        "Wind",
        "Kid",
        "Embassy",
        "Robot",
        "Note",
        "Ground",
        "Draft",
        "Ham",
        "War",
        "Mouse",
        "Center",
        "Chick",
        "China",
        "Bolt",
        "Spot",
        "Piano",
        "Pupil",
        "Plot",
        "Lion",
        "Police",
        "Head",
        "Litter",
        "Concert",
        "Mug",
        "Vacuum",
        "Atlantis",
        "Straw",
        "Switch",
        "Skyscraper",
        "Laser",
        "Scuba Diver",
        "Africa",
        "Plastic",
        "Dwarf",
        "Lap",
        "Life",
        "Honey",
        "Horseshoe",
        "Unicorn",
        "Spy",
        "Pants",
        "Wall",
        "Paper",
        "Sound",
        "Ice",
        "Tag",
        "Web",
        "Fan",
        "Orange",
        "Temple",
        "Canada",
        "Scorpion",
        "Undertaker",
        "Mail",
        "Europe",
        "Soul",
        "Apple",
        "Pole",
        "Tap",
        "Mouth",
        "Ambulance",
        "Dress",
        "Ice Cream",
        "Rabbit",
        "Buck",
        "Agent",
        "Sock",
        "Nut",
        "Boot",
        "Ghost",
        "Oil",
        "Superhero",
        "Code",
        "Kiwi",
        "Hospital",
        "Saturn",
        "Film",
        "Button",
        "Snowman",
        "Helicopter",
        "Loch Ness",
        "Log",
        "Princess",
        "Time",
        "Cook",
        "Revolution",
        "Shoe",
        "Mole",
        "Spell",
        "Grass",
        "Washer",
        "Game",
        "Beat",
        "Hole",
        "Horse",
        "Pirate",
        "Link",
        "Dance",
        "Fly",
        "Pit",
        "Server",
        "School",
        "Lock",
        "Brush",
        "Pool",
        "Star",
        "Jam",
        "Organ",
        "Berlin",
        "Face",
        "Luck",
        "Amazon",
        "Cast",
        "Gas",
        "Club",
        "Sink",
        "Water",
        "Chair",
        "Shark",
        "Jupiter",
        "Copper",
        "Jack",
        "Platypus",
        "Stick",
        "Olive",
        "Grace",
        "Bear",
        "Glass",
        "Row",
        "Pistol",
        "London",
        "Rock",
        "Van",
        "Vet",
        "Beach",
        "Charge",
        "Port",
        "Disease",
        "Palm",
        "Moscow",
        "Pin",
        "Washington",
        "Pyramid",
        "Opera",
        "Casino",
        "Pilot",
        "String",
        "Night",
        "Chest",
        "Yard",
        "Teacher",
        "Pumpkin",
        "Thief",
        "Bark",
        "Bug",
        "Mint",
        "Cycle",
        "Telescope",
        "Calf",
        "Air",
        "Box",
        "Mount",
        "Thumb",
        "Antarctica",
        "Trunk",
        "Snow",
        "Penguin",
        "Root",
        "Bar",
        "File",
        "Hawk",
        "Battery",
        "Compound",
        "Slug",
        "Octopus",
        "Whip",
        "America",
        "Ivory",
        "Pound",
        "Sub",
        "Cliff",
        "Lab",
        "Eagle",
        "Genius",
        "Ship",
        "Dice",
        "Hood",
        "Heart",
        "Novel",
        "Pipe",
        "Himalayas",
        "Crown",
        "Round",
        "India",
        "Needle",
        "Shop",
        "Watch",
        "Lead",
        "Tie",
        "Table",
        "Cell",
        "Cover",
        "Czech",
        "Back",
        "Bomb",
        "Ruler",
        "Forest",
        "Bottle",
        "Space",
        "Hook",
        "Doctor",
        "Ball",
        "Bow",
        "Degree",
        "Rome",
        "Plane",
        "Giant",
        "Nail",
        "Dragon",
        "Stadium",
        "Flute",
        "Carrot",
        "Wake",
        "Fighter",
        "Model",
        "Tokyo",
        "Eye",
        "Mexico",
        "Hand",
        "Swing",
        "Key",
        "Alien",
        "Tower",
        "Poison",
        "Cricket",
        "Cold",
        "Knife",
        "Church",
        "Board",
        "Cloak",
        "Ninja",
        "Olympus",
        "Belt",
        "Light",
        "Death",
        "Stock",
        "Millionaire",
        "Day",
        "Knight",
        "Pie",
        "Bed",
        "Circle",
        "Rose",
        "Change",
        "Cap",
        "Triangle"
    ]
    
    idiomPhrases = [
        "Heads Up",
        "No Ifs, Ands, or Buts",
        "Wake Up Call",
        "Down And Out",
        "Rain on Your Parade",
        "Right Off the Bat",
        "Throw In the Towel",
        "Quick and Dirty",
        "Burst Your Bubble",
        "Between a Rock and a Hard Place",
        "Hands Down",
        "Cry Over Spilt Milk",
        "Talk the Talk",
        "Curiosity Killed The Cat",
        "Head Over Heels",
        "High And Dry",
        "An Arm and a Leg",
        "Flea Market",
        "Keep Your Shirt On",
        "Ring Any Bells?",
        "Money Doesn't Grow On Trees",
        "Playing For Keeps",
        "A Dime a Dozen",
        "Down To The Wire",
        "Jaws of Death",
        "Knock Your Socks Off",
        "Barking Up The Wrong Tree",
        "Tug of War",
        "Happy as a Clam",
        "Top Drawer",
        "Keep On Truckin'",
        "Drive Me Nuts",
        "Yada Yada",
        "Down To Earth",
        "My Cup of Tea",
        "Elvis Has Left The Building",
        "Easy As Pie",
        "Playing Possum",
        "Quality Time",
        "Scot-free",
        "Jaws of Life",
        "Poke Fun At",
        "Know the Ropes",
        "Man of Few Words",
        "Not the Sharpest Tool in the Shed",
        "Son of a Gun",
        "When the Rubber Hits the Road",
        "Mountain Out of a Molehill",
        "Cup Of Joe",
        "If You Can't Stand the Heat, Get Out of the Kitchen",
        "Lickety Split",
        "Eat My Hat",
        "What Goes Up Must Come Down",
        "Jack of All Trades Master of None",
        "Ride Him, Cowboy!",
        "Close But No Cigar",
        "Keep Your Eyes Peeled",
        "Off One's Base",
        "Put a Sock In It",
        "Mouth-watering",
        "Give a Man a Fish",
        "Like Father Like Son",
        "Fit as a Fiddle",
        "Everything But The Kitchen Sink",
        "Shot In the Dark",
        "Go Out On a Limb",
        "All Greek To Me",
        "Roll With the Punches",
        "Back to Square One",
        "Greased Lightning",
        "A Chip on Your Shoulder",
        "Don't Count Your Chickens Before They Hatch",
        "Under Your Nose",
        "Raining Cats and Dogs",
        "Foaming At The Mouth",
        "Every Cloud Has a Silver Lining",
        "Under the Weather",
        "Birds of a Feather Flock Together",
        "Jumping the Gun",
        "Break The Ice",
        "Hard Pill to Swallow",
        "What Am I, Chopped Liver?",
        "Cut The Mustard",
        "Long In The Tooth",
        "Wild Goose Chase",
        "In a Pickle",
        "Two Down, One to Go",
        "Swinging For the Fences",
        "Lovey Dovey",
        "On the Same Page",
        "Cut To The Chase",
        "Knuckle Down",
        "On Cloud Nine",
        "Hit Below The Belt",
        "Goody Two-Shoes",
        "Jig Is Up",
        "Go For Broke",
        "Ugly Duckling",
        "Up In Arms",
        "The Plot Thickens"
    ]
    
    otherPhrases = [
        "A diamond is forever",
        "A drop in the bucket",
        "A drop in the ocean",
        "A fish out of water",
        "A fool's paradise",
        "A foot in the door",
        "À la carte",
        "À la mode",
        "A nest of vipers",
        "A no-brainer",
        "A priori",
        "A red rag to a bull",
        "A safe pair of hands",
        "A sea change",
        "A shot in the arm",
        "A sorry sight",
        "A stone's throw",
        "A tinker's damn",
        "A word in edgeways",
        "Abide with me",
        "About face",
        "About turn",
        "Above board",
        "Abracadabra",
        "Absent without leave",
        "Ace in the hole",
        "Achilles' heel",
        "Acid test",
        "Acronyms",
        "Across the board",
        "Act of God",
        "Action man",
        "Adam's ale",
        "Aga saga",
        "Against the grain",
        "Age before beauty",
        "Agree to disagree",
        "Aid and abet",
        "Air kiss",
        "Air quotes",
        "Al fresco",
        "Alive and kicking",
        "All agog",
        "All at sea",
        "All Greek to me",
        "All in all",
        "All of a sudden",
        "All things must pass",
        "All you can eat",
        "Alter ego",
        "Amber nectar",
        "An arm and a leg",
        "An axe to grind",
        "An ill wind",
        "An Oxford scholar",
        "Anchors aweigh",
        "Angry young man",
        "Ankle biter",
        "Annus horribilis",
        "Another think coming",
        "Apple pie order",
        "April fool",
        "Arms akimbo",
        "Arty-farty",
        "Auld lang syne",
        "Baby blues",
        "Baby boomer",
        "Baby father",
        "Back of beyond - The",
        "Back-seat driver",
        "Back the field",
        "Back to basics",
        "Back to square one",
        "Backroom boy",
        "Bad books",
        "Bad egg",
        "Bad hair day",
        "Badger to death",
        "Bag and baggage",
        "Baker's dozen",
        "Bald as a coot",
        "Bale out/bail out",
        "Ball and chain",
        "Bandy words",
        "Bane of your life",
        "Bang on about",
        "Baptism of fire",
        "Barking mad",
        "Barrel of laughs",
        "Basket case",
        "Bated breath",
        "Bats in the belfry",
        "Battle royal",
        "Be enthralled",
        "Beam ends - On your",
        "Bean counter",
        "Beast with two backs",
        "Beat a hasty retreat",
        "Beat around the bush",
        "Beck and call",
        "Bed of roses",
        "Bee in your bonnet",
        "Beef and reef",
        "Beer and skittles",
        "Bee's knees - The",
        "Beetle-browed",
        "Beg the question",
        "Beggar belief",
        "Bell the cat",
        "Belle of the ball",
        "Below the belt",
        "Below the salt",
        "Bells and whistles",
        "Belt and braces",
        "Belt up",
        "Best bib and tucker",
        "Better half",
        "Between two stools",
        "Beyond belief",
        "Beyond our ken",
        "Beyond the pale",
        "Biblical phrases",
        "Big Apple - The",
        "Big cheese - The",
        "Big Easy - The",
        "Big wig",
        "Billy-o - Like",
        "Billy no mates",
        "Binge drinking",
        "Bite the bullet",
        "Bite the dust",
        "Bitter end - The",
        "Black-on-black",
        "Blaze a trail",
        "Blind-man's buff",
        "Bling-bling",
        "Blonde bombshell",
        "Blood and thunder",
        "Bloody-minded",
        "Blow your mind",
        "Blown to smithereens",
        "Blue blood",
        "Blue-plate special",
        "Bob's your uncle",
        "Bode well",
        "Bodice ripper",
        "Body surfing",
        "Bog standard",
        "Bolt from the blue",
        "Bone dry",
        "Bone idle",
        "Bone up on",
        "Booby prize",
        "Booby trap",
        "Boogie-woogie",
        "Booze cruise",
        "Born again",
        "Boss eyed",
        "Bottle out",
        "Bottom drawer",
        "Bottom-up",
        "Bought the farm",
        "Bowled a maiden over",
        "Box and Cox",
        "Box-seat - in the",
        "Boxing Day",
        "Brand spanking new",
        "Brass monkey weather",
        "Bread of life - The",
        "Break a leg",
        "Break the ice",
        "Bricks and clicks",
        "Bring home the bacon",
        "Broad in the beam",
        "Brook no truck with",
        "Bronx cheer",
        "Brown as a berry",
        "Browned off",
        "Brownie points",
        "Brush - As daft as a",
        "Bubble and squeak",
        "Bucket list",
        "Buckle down",
        "Bugger Bognor!",
        "Buggins' turn",
        "Bums on seats",
        "Bun in the oven",
        "Bunch of fives - A",
        "Bunny boiler",
        "Bury the hatchet",
        "Busy as a bee",
        "Butter side down",
        "Butterfingers",
        "By and large",
        "By dint of",
        "By gum",
        "By hook or by crook",
        "By the board",
        "By the book",
        "By the short hairs",
        "By your leave",
        "Caesar Salad",
        "Call a spade a spade",
        "Canteen culture",
        "Canterbury pace",
        "Carbon-copy",
        "Carbon footprint",
        "Card-sharp",
        "Carey Street - On",
        "Carpe diem",
        "Carte blanche",
        "Cash on the nail",
        "Cast the first stone",
        "Cat got your tongue?",
        "Catch 22",
        "Cat's Cradle",
        "Caught red-handed",
        "Chaise lounge",
        "Chalk and cheese",
        "Champ at the bit",
        "Channel surfing",
        "Charley horse",
        "Charm offensive",
        "Charmed life",
        "Cheek by jowl",
        "Cherchez la femme",
        "Chew the cud",
        "Chick flick",
        "Chinese whispers",
        "Chinless wonder",
        "Chit-chat",
        "Chock-a-block",
        "Chop and change",
        "Chop-chop",
        "Chow down",
        "Christmas box - A",
        "Clear blue water",
        "Cleft stick - In a",
        "Cliff-hanger",
        "Cloak and dagger",
        "Clod-hopper",
        "Clog up",
        "Close, but no cigar",
        "Close quarters",
        "Cloud cuckoo land",
        "Cloud nine",
        "Club sandwich",
        "Clue - don't have a",
        "Clutch at straws",
        "Cobblers - A load of",
        "Cock-a-hoop",
        "Cock-sure",
        "Cock a snook",
        "Cock and bull story",
        "Cock-up",
        "Cogito ergo sum",
        "Coin a phrase",
        "Cold as any stone",
        "Cold comfort",
        "Cold feet",
        "Cold shoulder",
        "Cold turkey",
        "Collywobbles - The",
        "Colour up",
        "Come a cropper",
        "Come clean",
        "Come on down",
        "Come up trumps",
        "Come what come may",
        "Common sense",
        "Compassion fatigue",
        "Complete shambles",
        "Cook the books",
        "Cookie cutter",
        "Cool as a cucumber",
        "Cool Britannia",
        "Cop an attitude",
        "Copper-bottomed",
        "Cor blimey",
        "Cordon bleu",
        "Cotton on to",
        "Cotton-picking",
        "Counting sheep",
        "Country bumpkin",
        "Crack of doom - The",
        "Crackpot",
        "Crapper - The",
        "Crocodile tears",
        "Crop up",
        "Crown jewels",
        "Curate's egg",
        "Curry favour",
        "Cut and run",
        "Cut the mustard",
        "Cut to the chase",
        "Cute as a bug's ear",
        "Daft as a brush",
        "Damp squib",
        "Dance attendance on",
        "Darby and Joan",
        "Dark horse",
        "Darkest hour - The",
        "Dark side - The",
        "Darling buds of May",
        "Dash to pieces",
        "Date rape",
        "Davy Jones' locker",
        "Daylight robbery",
        "Dead as a dodo",
        "Dead as a doornail",
        "Dead cat bounce",
        "Dead ringer",
        "Derring-do",
        "Designer stubble",
        "Deus ex machina",
        "Devil to pay - The",
        "Devil's advocate",
        "Diamond in the rough",
        "Dicky-bird - Not a",
        "Die-hard",
        "Differently abled",
        "Dirt bag",
        "Dock your pay",
        "Doff your hat",
        "Dog days",
        "Dog in the manger",
        "Dog's bollocks",
        "Dog's breakfast",
        "Dog's dinner",
        "Doldrums - in the",
        "Dollars to doughnuts",
        "Done a runner",
        "Done to a turn",
        "Donkey's years",
        "Don't die like I did",
        "Don't go there",
        "Don't have a clue",
        "Doom and gloom",
        "Double cross",
        "Double Dutch",
        "Double entendre",
        "Double whammy",
        "Down at heel",
        "Down in the dumps",
        "Down to the wire",
        "Down the pan",
        "Down the tubes",
        "Drag race",
        "Draw a blank",
        "Draw your horns in",
        "Dreams of empire",
        "Dressed to the nines",
        "Drink like a fish",
        "Driving while black",
        "Drop-dead gorgeous",
        "Dropping like flies",
        "Ducks and drakes",
        "Dumb blonde",
        "Dust up",
        "Dutch - My old",
        "Dutch courage",
        "Duvet day",
        "Ear candy",
        "Ear-mark",
        "Easy as pie",
        "Eat humble pie",
        "Eat my hat",
        "Egg on",
        "Eighty six",
        "Elbow-grease",
        "Elephant in the room",
        "End of story",
        "Enough is enough",
        "Eponymous Phrases",
        "Et tu, Brute",
        "Ethnic cleansing",
        "Euphemisms",
        "Everybody out",
        "Excuse my French",
        "Face the music",
        "Faff about",
        "Faint-hearted",
        "Fair and square",
        "Fair dinkum",
        "Fair play",
        "Fair to middling",
        "Fairy-tale ending",
        "Fait accompli",
        "Fall from grace",
        "Fall guy",
        "Fall on your sword",
        "Fancy free",
        "Fancy pants",
        "Fanny Adams - Sweet",
        "Far be it from me",
        "Farmers",
        "Fashion victim",
        "Fast and loose",
        "Fast asleep",
        "Fathom out",
        "Fed up",
        "Feeding frenzy",
        "Fell swoop - At one",
        "Fellow traveller",
        "Fend off",
        "Fiddlesticks",
        "Field day",
        "Fifth column",
        "Fight fire with fire",
        "Fight the good fight",
        "Filthy rich",
        "Finagle's Law",
        "Fine as frog's hair",
        "Finger lickin good",
        "Fingers and thumbs",
        "First water",
        "First World",
        "Fish or cut bait",
        "Fit as a fiddle",
        "Fifth column",
        "Fifth estate",
        "Fits and starts",
        "Fits to a tee",
        "Five o'clock shadow",
        "Fixer-upper",
        "Flash in the pan",
        "Flat out",
        "Flavor of the month",
        "Flesh and blood",
        "Flotsam and jetsam",
        "Fly in the ointment",
        "Fly off the handle",
        "Fly on the wall",
        "Foam at the mouth",
        "Fobbed off",
        "Fool's errand",
        "Fool's gold",
        "Fool's paradise - A",
        "Foot in the door - A",
        "For crying out loud",
        "For ever and a day",
        "For good measure",
        "For keeps",
        "For the birds",
        "Forbidden fruit",
        "Foregone conclusion",
        "Forlorn hope",
        "Foul play",
        "Four by two",
        "French phrases",
        "Friday afternoon car",
        "From pillar to post",
        "Fruits of your loins",
        "Fuddy-duddy",
        "Full Monty - The",
        "Full tilt",
        "Full to the gunwales",
        "Funny farm",
        "Fuzzy wuzzy",
        "Game is afoot - The",
        "Game is up - The",
        "Game of two halves",
        "Gee whiz",
        "Generation X",
        "Get medieval",
        "Get on my wick",
        "Get one's dander up",
        "Get over it",
        "Get the pip",
        "Get the sack",
        "Get the upper hand",
        "Get underway",
        "Get used to it",
        "Get your dander up",
        "Get your goat",
        "Giddy aunt",
        "Giddy goat",
        "Gild the lily",
        "Ginned up",
        "Ginger",
        "Ginger up",
        "Give a wide berth",
        "Give no quarter",
        "Give up the ghost",
        "Glass ceiling",
        "Gloom and doom",
        "Go berserk",
        "Go by the board",
        "Go by the book",
        "Go Dolally",
        "Go-faster",
        "Go for a burton",
        "Go haywire",
        "Go like the clappers",
        "Go off half-cocked",
        "Go out on a limb",
        "Go postal",
        "Go pound sand",
        "Go the whole hog",
        "Go to pot",
        "Go to the dogs",
        "Go to the mattresses",
        "Go whole hog",
        "God is dead",
        "God rot them",
        "Godfrey Daniel",
        "Going for a burton",
        "Gone for a burton",
        "Good as gold",
        "Good in parts",
        "Good measure - For",
        "Good men and true",
        "Good riddance",
        "Good Samaritan",
        "Goody two-shoes",
        "Gordon Bennett",
        "Got my mojo working",
        "Grand slam",
        "Grandfather clock",
        "Granny dumping",
        "Grasp the nettle",
        "Grass up",
        "Graveyard shift",
        "Greased lightning",
        "Great balls of fire",
        "Great unwashed - the",
        "Green eyed monster",
        "Gregory Peck",
        "Gridlock",
        "Grind to a halt",
        "Grist to the mill",
        "Guinea pig",
        "Gung ho",
        "Gussied-up",
        "Guts for garters",
        "Hairy eyeball",
        "Halcyon days",
        "Half-cocked",
        "Half-hearted",
        "Half inch",
        "Hand over fist",
        "Hands down",
        "Hanky-panky",
        "Happy as a clam",
        "Happy as a sandboy",
        "Happy as Larry",
        "Happy clappy",
        "Happy slapping",
        "Harbinger of doom",
        "Hard and fast",
        "Hard cheese",
        "Hard hearted",
        "Hard lines",
        "Harp on",
        "Harvest moon",
        "Hasta la vista, baby",
        "Haste makes waste",
        "Hat trick",
        "Have a Captain Cook",
        "Have a dekko",
        "Have an axe to grind",
        "Have an inkling",
        "Have no truck with",
        "Haven't got a clue",
        "Head over heels",
        "Heads up",
        "Hear hear",
        "Heart's content",
        "Heavens to Betsy",
        "Heavy metal",
        "Heebie-jeebies - The",
        "Hedge your bets",
        "Hell in a handbasket",
        "Hell or high water",
        "Helter-skelter",
        "Het up",
        "Higgledy-piggledy",
        "High and dry",
        "High and mighty",
        "High as a kite",
        "High five",
        "High-flyer",
        "High on the hog",
        "High time",
        "Hissy fit",
        "History is bunk",
        "Hit the hay",
        "Hither and yon",
        "Hobson's choice",
        "Hobby-horse",
        "Hocus pocus",
        "Hoi polloi",
        "Hoity-toity",
        "Hold your horses",
        "Homonyms",
        "Hooray Henry",
        "Horse and cart",
        "Horse feathers",
        "Horse-sense",
        "Hot-blooded",
        "Hot off the press",
        "Hot on the heels",
        "Household words",
        "How do you do?",
        "How now brown cow?",
        "Hugger-mugger",
        "Hunky-dory",
        "Hunt and peck",
        "Hush puppies",
        "I haven't got a clue",
        "I will swing for you",
        "Identity theft",
        "If I had my druthers",
        "If the cap fits",
        "If the shoe fits",
        "Ill wind",
        "I'm stumped",
        "In a cleft stick",
        "In a pickle",
        "In a pig's eye",
        "In a quandary",
        "In a nutshell",
        "In a trice",
        "In like Flynn",
        "In limbo",
        "In my minds eye",
        "In spades",
        "In stitches",
        "In the bag",
        "In the box-seat",
        "In the buff",
        "In the cart",
        "In the catbird seat",
        "In the club",
        "In the doghouse",
        "In the doldrums",
        "In the limelight",
        "In the nick of time",
        "In the pink",
        "In the red",
        "In the same boat",
        "In your face",
        "Indian giver",
        "Indian summer",
        "Infra dig",
        "Inside out",
        "Iron hoof",
        "Is the Pope Polish?",
        "It's all Greek to me",
        "It's that man again",
        "Ivory tower",
        "Jack in the box",
        "Jack Palancing",
        "Jack the lad",
        "Jam tomorrow",
        "Jerry built",
        "Jet-black",
        "Jimmy Horner",
        "Jimmy Riddle",
        "Jobs for the boys",
        "Join the colours",
        "Joined at the hip",
        "Johnny on the spot",
        "Jot or tittle",
        "Jump the gun",
        "Jump the shark",
        "Jury is still out",
        "Just deserts",
        "Just in time",
        "Kangaroo court",
        "Katy bar the door",
        "Keep a wide berth",
        "Keen as mustard",
        "Keep schtum",
        "Keep at bay",
        "Keep your chin up",
        "Keep your distance",
        "Keep your nose clean",
        "Keep your pecker up",
        "Keep your powder dry",
        "Keepy-uppy",
        "Kettle of fish",
        "Khyber pass",
        "Kick the bucket",
        "Kick your heels",
        "Kickin' - Alive and",
        "Kilroy was here",
        "Kiss and tell",
        "Kiss me Hardy",
        "Knee-jerk reaction",
        "Knick-knack",
        "Knock back",
        "Knock off",
        "Knock on wood",
        "Know the ropes",
        "Know your onions",
        "Knuckle down",
        "Knuckle under",
        "Kowtow to",
        "La-di-da",
        "La dolce vita",
        "Labour of love",
        "Lackadaisical",
        "Ladies' room",
        "Lager frenzy",
        "Laid out in lavender",
        "La-la land",
        "Lame duck",
        "Land of nod - The",
        "Lardy-dardy",
        "Lark about",
        "Last but not least",
        "Last straw - The",
        "Latin Phrases",
        "Laugh like a drain",
        "Laughing-stock",
        "The law is an ass",
        "Lead-pipe cinch",
        "Learn the ropes",
        "Left in the lurch",
        "Less is more",
        "Let or hindrance",
        "Let them eat cake",
        "Let there be light",
        "Let your hair down",
        "Let's roll",
        "Level playing field",
        "Lick and a promise",
        "Lick into shape",
        "Lickety-split",
        "Lie low",
        "Life begins at forty",
        "Life of Riley",
        "Life's too short",
        "Like billy-o",
        "Like it or lump it",
        "Like the clappers",
        "Like the Dickens",
        "Lily-livered",
        "Lions led by donkeys",
        "Living daylights",
        "Lo and behold",
        "Load of cobblers",
        "Load of codswallop",
        "Loaf of bread",
        "Local derby",
        "Long in the tooth",
        "Look before you leap",
        "Loose cannon",
        "Lose face",
        "Lose your marbles",
        "Love is blind",
        "Loved-up",
        "Lunatic fringe",
        "Mad as a hatter",
        "Mad as a March hare",
        "Magical realism",
        "Main chance",
        "Make a bee-line for",
        "Make a pig's ear of",
        "Make haste",
        "Make my day",
        "Make no bones about",
        "Mal de mer",
        "Many happy returns",
        "'March' phrases",
        "Mare's nest",
        "Marital aid",
        "Market forces",
        "McCoy - The real",
        "Mea culpa",
        "Meat and drink",
        "Meat and two veg.",
        "Meet your Waterloo",
        "Men in suits",
        "Mend fences",
        "Ménage à trois",
        "Merry Christmas",
        "Method in my madness",
        "Mexican wave",
        "Mickey Finn",
        "Middle for diddle",
        "Middle of the road",
        "Might and main",
        "Minced oaths",
        "Minced words",
        "Mind your Ps and Qs",
        "Mind's ear",
        "Mind's eye",
        "Mint condition",
        "Misquotes",
        "Moaning Minnie",
        "Mondegreens",
        "Montezuma's Revenge",
        "'Money' phrases",
        "Money for old rope",
        "Monty - The full",
        "Moot point",
        "Morbid obesity",
        "More fool you",
        "More light!",
        "Morning person",
        "Mother country",
        "Motley crew",
        "Mouth-watering",
        "Movable feast",
        "Movers and shakers",
        "Moving the goalposts",
        "Much of a muchness",
        "Mud - your name is",
        "Multitude of sins",
        "Mumbo jumbo",
        "Mum's the word",
        "Murphy's Law",
        "Mutt's nuts - The",
        "Mutt and Jeff",
        "My bad",
        "My better half",
        "My cup of tea",
        "My cup runneth over",
        "My giddy aunt",
        "My husband and I",
        "My mind's eye",
        "My old china",
        "My old Dutch",
        "My salad days",
        "My stars and garters",
        "Namby-pamby",
        "Name and shame",
        "Name is mud",
        "Nautical phrases",
        "Near the knuckle",
        "Ne'er do well",
        "Needs must",
        "Nest-egg",
        "Nest of vipers - A",
        "Never-never land",
        "New kid on the block",
        "Nice as ninepence",
        "Nice kettle of fish",
        "Night owl",
        "Nine days' wonder",
        "Nip and tuck",
        "Nip in the bud",
        "Nitty-gritty",
        "No-brainer",
        "No dice",
        "No holds barred",
        "No laughing matter",
        "No man is an island",
        "No quarter given",
        "No truck with",
        "No way, Jose",
        "Nod - The land of",
        "Norange - A",
        "Nosy parker",
        "Not a dicky-bird",
        "Not by a long chalk",
        "Not my cup of tea",
        "Not rocket science",
        "Not worth the candle",
        "Nth degree",
        "Nul points",
        "Nutshell - In a",
        "Odds bodkins",
        "Off his own bat",
        "Off the record",
        "Off with his head",
        "Offing - In the",
        "Okay",
        "Okey-dokey",
        "Old as Methuselah",
        "Old as the hills",
        "Old chestnut",
        "Old codger",
        "Old hat",
        "On Carey Street",
        "On cloud nine",
        "On queer street",
        "On tenterhooks",
        "On the ball",
        "On the bubble",
        "On the button",
        "On the dole",
        "On the fiddle",
        "On the pig's back",
        "On the QT",
        "On the wagon",
        "On the warpath",
        "On with the motley",
        "On your beam ends",
        "On your tod",
        "Once in a blue moon",
        "One-hit wonder",
        "One fell swoop - At",
        "One for the road",
        "One over the eight",
        "One stop shop",
        "Oops-a-daisy",
        "Open season",
        "Out of sight",
        "Out of sorts",
        "Out on a limb",
        "Over a barrel",
        "Over the moon",
        "Over the top",
        "Oxo cube",
        "Paint the town red",
        "Panic stations",
        "Paper tiger",
        "Pass the buck",
        "Paying guest - A",
        "Pearls before swine",
        "Pears for your heirs",
        "Peeping Tom",
        "Peg out",
        "Pell-mell",
        "Pennies from heaven",
        "Penny dreadful",
        "(The) penny drops",
        "Penny pinching",
        "Pester power",
        "Peter out",
        "Petty cash",
        "Pick 'n' mix",
        "Picture-perfect",
        "Pie - as easy as",
        "Pie in the sky",
        "Piece of cake - A",
        "Piece of piss",
        "Piece of the action",
        "Pig in a poke",
        "Pigeon-chested",
        "Pig's back - on the",
        "Pig's ear",
        "(In a) pig's eye",
        "Pig and whistle",
        "Piggyback",
        "Pigs might fly",
        "Pin money",
        "Pipe down",
        "Pipe dream - A",
        "Piping hot",
        "Pitch black",
        "Pitch dark",
        "Plain sailing",
        "Plates of meat",
        "Play by ear",
        "Play fast and loose",
        "Play it again Sam",
        "Play second fiddle",
        "Play silly buggers",
        "Play the giddy goat",
        "Play the race card",
        "Pleased as Punch",
        "Plug-ugly",
        "Plugged nickel",
        "Poetic justice",
        "Point-and-click",
        "Politically correct",
        "Point-blank",
        "Point to point",
        "Pommy bashing",
        "Pond life",
        "Pony and trap",
        "Pony up",
        "Pop goes the weasel",
        "Pork pies",
        "Take potluck",
        "Pound of flesh",
        "Power dressing",
        "Powers that be - The",
        "Preposterous",
        "Press into service",
        "Pretty penny - A",
        "Prick up your ears",
        "Prime time",
        "Primrose path",
        "Proverbs - A list of",
        "Pull in your horns",
        "Pull up stakes",
        "Pull your horns in",
        "Pull your finger out",
        "Pulling one's leg",
        "Purple patch",
        "Push the boat out",
        "Push the envelope",
        "Put a damper on",
        "Put a sock in it",
        "Put paid to",
        "Put the mockers on",
        "Put up your dukes",
        "Put your back up",
        "Pyrric victory",
        "Quality time",
        "Quarter - Give no",
        "Queer Street",
        "Queer the pitch",
        "Quid pro quo",
        "Quotations",
        "Rabbit and pork",
        "Rack and ruin",
        "Rag-and-bone man",
        "Rack your brains",
        "Rag, tag and bobtail",
        "Raining stair-rods",
        "Raise Cain",
        "Rank and file",
        "Raspberry tart",
        "Raze to the ground",
        "Rat arsed",
        "Read the riot act",
        "Real McCoy",
        "Red-handed (caught)",
        "Red herring",
        "Red-letter day",
        "Red sky at night ...",
        "Red tape",
        "Reduplicated phrases",
        "Rest on his laurels",
        "Rhyme nor reason",
        "Rhyming slang",
        "Richard the Third",
        "Riding shotgun",
        "Riff-raff",
        "Riley - the life of",
        "[That] Rings a bell",
        "Ring-fencing",
        "Ring the changes",
        "Rinky-dink",
        "Rise and shine",
        "Road apples",
        "Road rage",
        "Roasted to a turn",
        "Rock and roll",
        "Rosie Lea",
        "Rough diamond",
        "Round Robin",
        "Route one",
        "Rub of the green",
        "Rule of thumb",
        "Rum do",
        "Rumpy-pumpy",
        "Run a mile",
        "Run amok",
        "Run of the mill",
        "Run out of steam",
        "Run rings around",
        "Run the gauntlet",
        "Sacred cow",
        "Safe as houses - As",
        "Safe sex",
        "Salad days",
        "San fairy Ann",
        "Save face",
        "Save one's bacon",
        "Saved by the bell",
        "Savoir faire",
        "Say cheese",
        "Say goodnight Gracie",
        "Scapegoat",
        "Scarper",
        "Scot-free",
        "Sea change",
        "Second-guess",
        "Security blanket",
        "See red",
        "Seen better days",
        "Send packing",
        "Senior citizen",
        "Sent to Coventry",
        "Set one's cap at",
        "Sex and shopping",
        "Seven-year itch",
        "Sexton Blake",
        "Shebang - The whole",
        "Shaggy dog story",
        "Shake a leg",
        "Shakers and movers",
        "Shambles",
        "Shilly-shally",
        "Shit for brains",
        "Shiver my timbers",
        "Shoddy",
        "Shot across the bows",
        "Shot in the arm",
        "Shot in the dark",
        "Shoot through",
        "Short shrift",
        "Show your mettle",
        "Shrinking violet",
        "Shut your cake-hole",
        "Siamese twins",
        "Sick puppy (A)",
        "Silly Billy",
        "Silly season",
        "Silence is golden",
        "Silver bullet",
        "Similes",
        "Sitting pretty",
        "Skid row",
        "Skin and blister",
        "Sleep like a top",
        "Sleep tight",
        "Sleeveless errand",
        "Sloane Ranger",
        "Slush fund",
        "Smart casual",
        "Smoke and mirrors",
        "So sue me",
        "Soap-dodger",
        "Sod's Law",
        "Sold down the river",
        "Son of a bitch",
        "Son of a gun",
        "Sorry sight",
        "Sound bite",
        "Sound out",
        "Sour grapes",
        "Speak of the Devil",
        "Special relationship",
        "Spelling-bee",
        "Spend a penny",
        "Spick and span",
        "Spill the beans",
        "Spin doctor",
        "Spitting feathers",
        "Spitting image",
        "Spoonerisms",
        "Spruce-up",
        "Square meal",
        "Squeaky bum time",
        "Stand and deliver",
        "Stand up guy",
        "Star-crossed lovers",
        "Stark, raving mad",
        "Start from scratch",
        "Steal a march",
        "Steal my thunder",
        "Stick in the mud",
        "Sticky wicket",
        "Stiff upper lip",
        "Stiffen the sinews",
        "Stinking rich",
        "Stone the crows",
        "Stone's throw",
        "Stony-hearted",
        "Stool pigeon",
        "Storm in a teacup",
        "Straight as a die",
        "Strain at the leash",
        "Strait-laced",
        "Strait and narrow",
        "Stranger danger",
        "Stuff and nonsense",
        "Stump up",
        "Such is life",
        "Surf and turf",
        "Swan song",
        "Sweet Fanny Adams",
        "Swing for you",
        "Swing the lead",
        "Take a back seat",
        "Take potluck",
        "Take the cake",
        "Take the Mickey",
        "Take the upper hand",
        "Take umbrage",
        "Taken aback",
        "Talk of the Devil",
        "Talk the talk",
        "Talk to the hand",
        "Tall story",
        "Tawdry",
        "Tea leaf",
        "Technicolor yawn",
        "Tempest in a teapot",
        "That's all folks!",
        "That's all she wrote",
        "The apple of my eye",
        "The back of beyond",
        "The balance of power",
        "The balance of trade",
        "The bane of my life",
        "The bee's knees",
        "The Big Apple",
        "The Big Easy",
        "The bitter end",
        "The bread of life",
        "The buck stops here",
        "The call of the wild",
        "The collywobbles",
        "The crack of doom",
        "The Crapper",
        "The cut of your jib",
        "The dark side",
        "The Devil Incarnate",
        "The Devil to pay",
        "The fat of the land",
        "The fifth estate",
        "The full monty",
        "The game is afoot",
        "The game is up",
        "The great unwashed",
        "The hairy eyeball",
        "The heebie-jeebies",
        "The land of nod",
        "The last straw",
        "The law is an ass",
        "The life of Riley",
        "The living daylights",
        "The more the merrier",
        "The mutt's nuts",
        "The nth degree",
        "The powers that be",
        "The real McCoy",
        "The seven-year itch",
        "The sky's the limit",
        "The third degree",
        "The upper hand",
        "The usual suspects",
        "The whole nine yards",
        "The whole shebang",
        "The year dot",
        "The Yellow Peril",
        "Thick and thin",
        "As thick as thieves",
        "Thinking cap",
        "Third degree - The",
        "Third time lucky",
        "Thorn in the flesh",
        "Thou shalt not kill",
        "Three score and ten",
        "Throw in the towel",
        "Thumbs up",
        "Ticked off",
        "Tickle the ivories",
        "Tickled pink",
        "Tide over",
        "Tie the knot",
        "Tinker's damn",
        "Tilting at windmills",
        "Tissue of lies",
        "Titfer",
        "Tit for tat",
        "Tits up",
        "To a T",
        "To beggar belief",
        "To boot",
        "To the manner born",
        "To the nth degree",
        "Toast of the town",
        "Toe the line",
        "Toe-curling",
        "Toffee-nosed",
        "Tommy Atkins",
        "Tongue in cheek",
        "Toodle-oo",
        "Tooth and nail",
        "Top dog",
        "Top drawer",
        "Top notch",
        "Topsy-turvy",
        "Total shambles",
        "Touch and go",
        "Touch wood",
        "Touchy-feely",
        "Tout de suite",
        "Tower of strength",
        "Train surfing",
        "Trick or treat",
        "Trouble and strife",
        "True blue",
        "Truth will out",
        "Tuckered out",
        "Turn a blind eye",
        "Turn of phrase",
        "Turn the tables",
        "Turn up trumps",
        "Twenty three skidoo",
        "Twenty four seven",
        "Two cents worth",
        "Two peas in a pod",
        "Under the thumb",
        "Get - underway",
        "Union Jack",
        "The great - unwashed",
        "Up a blind alley",
        "Up a gum tree",
        "Up the duff",
        "Up the pole",
        "Up to snuff",
        "Upper crust",
        "Upper hand",
        "Up in arms",
        "Ups-a-daisy",
        "Upset the apple-cart",
        "Up the ante",
        "Upside down",
        "Urban myth",
        "Use your loaf",
        "Usual suspects - The",
        "Van surfing",
        "Vanish into thin air",
        "Veg out",
        "Vice versa",
        "Vicious circle",
        "Vis-a-vis",
        "Walk free",
        "Walk the walk",
        "Walk the plank",
        "Warts and all",
        "Watch the birdie",
        "Watching brief",
        "Wax lyrical",
        "Wax poetic",
        "We are a grandmother",
        "We are not amused",
        "Wear the trousers",
        "Weasel words",
        "Wee-wee",
        "Well heeled",
        "Well read",
        "Wet behind the ears",
        "Wet blanket",
        "What are you like?",
        "What's not to like?",
        "What's up Doc?",
        "When pigs fly",
        "Whet your appetite",
        "Which is which?",
        "Whip round",
        "Whipper snapper",
        "Whipping boy",
        "Whistle and flute",
        "Whistle blower",
        "White as snow",
        "White bread",
        "White elephant",
        "Whole-hearted",
        "Whole shebang - The",
        "Whoops-a-daisy",
        "Wick - you get on my",
        "Wide berth - Keep a",
        "Wild and woolly",
        "Wild goose chase",
        "Willy nilly",
        "Win hands down",
        "Wing it",
        "Winter drawers on",
        "Wish you were here",
        "With bells on",
        "Woe betide you",
        "Woe is me",
        "Word for word",
        "Word in edgeways - A",
        "Words ending in gry",
        "Worse for wear",
        "Worth one's salt",
        "Wotcher",
        "Wreak havoc",
        "Yada yada",
        "Year dot - The",
        "Yellow-belly",
        "Yellow Peril",
        "You are what you eat",
        "You get on my wick",
        "Young turk",
        "Your name is mud",
        "Zero tolerance",
        "Zig-zag"
    ]
    /* upon initialization, generate a random word */
    constructor(props){
        super(props);
        let word = this.getRandom(this.codenamesList);
        this.setNewWords();
    }
    getRandom = list => {
        let len = list.length;
        let index = Math.floor(Math.random()*len); // 0 to len-1
        return list[index];
    }
    setNewWords = () => {
        let singleWord = this.getRandom(this.codenamesList);
        let phrase = this.getRandom(this.idiomPhrases);
        let otherphrase = this.getRandom(this.otherPhrases);
        // let combined = singleWord + "<br>" + phrase;
        this.props.setSecretWords([singleWord,phrase,otherphrase]);
    }

    mouseListener = undefined;
    touchListener = undefined;
    showUntilReleased = () => {
        this.props.showFn();
        this.mouseListener = document.addEventListener("mouseup",()=>{
            this.props.hideFn();
            document.removeEventListener("touchend",this.touchListener);
        },{once:true})
        this.touchListener = document.addEventListener("touchend",()=>{
            this.props.hideFn();
            document.removeEventListener("mouseup",this.mouseListener);
        },{once:true})
    }

    newConceptClickDown = () => {
        // this.props.selectFn(this.codenamesList);
        this.setNewWords()
        this.showUntilReleased();
    }
    newConceptTouchDown = this.newConceptClickDown;

    render(){
        let codewords = this.props.secretWords.map(word=>{
            return <p>{word}.</p>
        })
        let secretWordBox;

        if(this.props.isHidden === "hidden"){
            secretWordBox = <button type="button" className="secretWordButton" onMouseDown={this.showUntilReleased} onTouchStart={this.showUntilReleased}>Show Secret Words </button>
        }
        else{
            secretWordBox = <div className="secretWordContainer" onMouseDown={this.showUntilReleased} onTouchStart={this.showUntilReleased}>
                {codewords}
            </div>
        }
        return(
            <div className="noselect"> 
                <button type="button" onMouseDown={this.newConceptClickDown} onTouchStart={this.newConceptTouchDown}>
                    New Concept
                </button>
                
                {secretWordBox}
            </div>
        )
    }
    
}

export default WordLists;


// const undercoverList: string[] = [
//     /* Words that I've added */
//     "Cuckold",
//     /* Words from the game */
//     "Horse",
//     "Sauna",
//     "Hooker",
//     "Stool",
//     "Mouth",
//     "Touchdown",
//     "Snake",
//     "Whiskey",
//     "Pickle",
//     "Hose",
//     "Legend",
//     "Blush",
//     "Dick",
//     "Cock",
//     "Alcohol",
//     "Sausage",
//     "Pecker",
//     "Straight",
//     "Sore",
//     "Toy",
//     "Black",
//     "White",
//     "Period",
//     "Couch",
//     "Juice",
//     "Bra",
//     "Dame",
//     "Chick",
//     "Bitch",
//     "Score",
//     "Sheep",
//     "Strap",
//     "Mattress",
//     "Train",
//     "Bondage",
//     "Wiener",
//     "Penis",
//     "Furry",
//     "Joystick",
//     "Apples",
//     "Condom",
//     "Bisexual",
//     "Hole",
//     "Secretary",
//     "Roll",
//     "Strip",
//     "Freak",
//     "Tramp",
//     "Foreskin",
//     "Wine",
//     "Pee",
//     "Experiment",
//     "Johnson",
//     "Banana",
//     "Clam",
//     "Blow",
//     "Balloon",
//     "Semen",
//     "Regret",
//     "Stripper",
//     "Homerun",
//     "Trim",
//     "Bar",
//     "Wood",
//     "Paddle",
//     "Cowgirl",
//     "John",
//     "Candle",
//     "Cigarette",
//     "Cigar",
//     "Knob",
//     "Sex",
//     "Gang",
//     "Stud",
//     "Screw",
//     "Trousers",
//     "Safe",
//     "Girl",
//     "Package",
//     "Grope",
//     "Jewels",
//     "Beach",
//     "Chubby",
//     "Beef",
//     "Bender",
//     "Shaft",
//     "Peaches",
//     "Swallow",
//     "Flower",
//     "Trunk",
//     "Sack",
//     "Job",
//     "Onion",
//     "Bowl",
//     "Jerk",
//     "Crap",
//     "Bush",
//     "Box",
//     "Mushroom",
//     "Shame",
//     "Couple",
//     "Sweat",
//     "Strobe",
//     "Tubesteak",
//     "Rug",
//     "Butt",
//     "Nylon",
//     "Lick",
//     "Hotel",
//     "Boy",
//     "Boob",
//     "Biscuits",
//     "Fatty",
//     "Share",
//     "Slut",
//     "Swimmers",
//     "Pound",
//     "Tuna",
//     "Roach",
//     "Brownie",
//     "Nuts",
//     "Blonde",
//     "Horny",
//     "Catcher",
//     "Body",
//     "Dominate",
//     "Mole",
//     "Shave",
//     "Orgasm",
//     "Taboo",
//     "Roof",
//     "Twig",
//     "Red",
//     "Lube",
//     "Nude",
//     "Eat",
//     "Hooters",
//     "Legs",
//     "Behind",
//     "Olive",
//     "Brown",
//     "Shower",
//     "Oyster",
//     "Taco",
//     "Salad",
//     "Udders",
//     "Rave",
//     "Inch",
//     "Nipple",
//     "Gay",
//     "High",
//     "Booze",
//     "Beaver",
//     "Pussy",
//     "Ice",
//     "Skank",
//     "Melons",
//     "Tail",
//     "Rack",
//     "Uranus",
//     "Queer",
//     "Lingerie",
//     "Needle",
//     "Escort",
//     "Herb",
//     "Bear",
//     "Beans",
//     "Log",
//     "Hamster",
//     "Skirt",
//     "Gigolo",
//     "Tap",
//     "Pie",
//     "Vasectomy",
//     "Queen",
//     "Group",
//     "Necklace",
//     "Commando",
//     "Headlights",
//     "Ashes",
//     "Bacon",
//     "Goose",
//     "Pillows",
//     "Smell",
//     "Latex",
//     "Tavern",
//     "Smegma",
//     "Vegas",
//     "Queef",
//     "Hot",
//     "Navel",
//     "Gag",
//     "Headboard",
//     "Bed",
//     "Ass",
//     "Caboose",
//     "Carpet",
//     "Smoke",
//     "Cuffs",
//     "Teabag",
//     "Shot",
//     "Vein",
//     "Purple",
//     "Gash",
//     "Nail",
//     "Hand",
//     "Head",
//     "Chaps",
//     "Animal",
//     "Koozie",
//     "Fish",
//     "Snatch",
//     "Rookie",
//     "Tease",
//     "Snort",
//     "Vibrator",
//     "Pucker",
//     "Film",
//     "Mug",
//     "Bang",
//     "Hammer",
//     "Grandma",
//     "Grass",
//     "Sniff",
//     "Prick",
//     "Tent",
//     "Baked",
//     "Video",
//     "Pub",
//     "G-Spot",
//     "Movie",
//     "Jazz",
//     "Friction",
//     "Eyes",
//     "Drunk",
//     "Softballs",
//     "Kitty",
//     "Tequila",
//     "Bottom",
//     "Vinyl",
//     "Prostate",
//     "Chains",
//     "Motorboat",
//     "Crabs",
//     "French",
//     "Hurl",
//     "Cheek",
//     "Solo",
//     "Lizard",
//     "Threesome",
//     "Breast",
//     "Virgin",
//     "Prison",
//     "Donkey",
//     "Monkey",
//     "Douche",
//     "Freckles",
//     "Bond",
//     "Keg",
//     "Spank",
//     "Boxers",
//     "Throat",
//     "Pinch",
//     "Vodka",
//     "Pot",
//     "Lips",
//     "Mom",
//     "Finger",
//     "Fluff",
//     "Bling",
//     "Rectum",
//     "Speed",
//     "Missionary",
//     "Tickle",
//     "Sin",
//     "Vomit",
//     "Porn",
//     "Cuddle",
//     "Moist",
//     "Manboobs",
//     "Flash",
//     "Dildo",
//     "Cocktail",
//     "Sperm",
//     "Emission",
//     "tie",
//     "Diarrhea",
//     "Wad",
//     "Pork",
//     "Bottle",
//     "Mixer",
//     "Crack",
//     "Fist",
//     "Club",
//     "Cucumber",
//     "Spoon",
//     "Seed",
//     "Tip",
//     "Intern",
//     "Wang",
//     "Pole",
//     "Champagne",
//     "Milk",
//     "Loose",
//     "Fire",
//     "Choke",
//     "Noodle",
//     "Spread",
//     "Doggy",
//     "Tit",
//     "Beer",
//     "Waste",
//     "Poker",
//     "Gerbil",
//     "Member",
//     "Bartender",
//     "Fetish",
//     "Bone",
//     "Motel",
//     "Squirt",
//     "Lotion",
//     "Tongue",
//     "Flesh",
//     "Watch",
//     "Player",
//     "Balls",
//     "Meat",
//     "Cream",
//     "Fecal",
//     "Rubber",
//     "Kinky",
//     "Stalker",
//     "Bust",
//     "Tool",
//     "Skid",
//     "Wax",
//     "Pitcher",
//     "Knees",
//     "Martini",
//     "Lobster",
//     "Feather",
//     "Booty",
//     "Joint",
//     "Steamy",
//     "Mesh",
//     "Top",
//     "Facial",
//     "Weed",
//     "Pipe",
//     "Cherry",
//     "Lust",
//     "Knockers",
//     "Fantasy",
//     "Hump",
//     "Poop",
//     "Stiff",
//     "Nurse",
//     "Torture",
//     "Bong",
//     "Wench",
//     "Pink",
//     "Gangbang",
//     "Love",
//     "Coyote",
//     "Drill",
//     "Acid",
//     "Line",
//     "Stiletto",
//     "Turd",
//     "Touch",
//     "Daddy",
//     "Wet",
//     "Pimp",
//     "Hell",
//     "Liquor",
//     "Burn",
//     "Drag",
//     "Cougar",
//     "Briefs",
//     "Stones",
//     "Naked",
//     "Orgy",
//     "Chest",
//     "Whip",
//     "Pig",
//     "Jugs",
//     "Lighter",
//     "Cannons",
//     "Down",
//     "Clap"
// ]

// const duetList: string[] = [
//     "Drum",
//     "Bride",
//     "Wagon",
//     "University",
//     "Hit",
//     "Ash",
//     "Bass",
//     "Astronaut",
//     "Doll",
//     "Nerve",
//     "Coach",
//     "Beam",
//     "Spoon",
//     "Country",
//     "Nose",
//     "King Arthur",
//     "Stamp",
//     "Camp",
//     "Brain",
//     "Leaf",
//     "Tutu",
//     "Coast",
//     "Lunch",
//     "Thunder",
//     "Potato",
//     "Desk",
//     "Onion",
//     "Elephant",
//     "Anchor",
//     "Cowboy",
//     "Flood",
//     "Mohawk",
//     "Santa",
//     "Pitcher",
//     "Barbecue",
//     "Leather",
//     "Skates",
//     "Musketeer",
//     "Snap",
//     "Saddle",
//     "Genie",
//     "Mark",
//     "Shoulder",
//     "Governor",
//     "Manicure",
//     "Anthem",
//     "Halloween",
//     "Newton",
//     "Balloon",
//     "Fiddle",
//     "Craft",
//     "Glacier",
//     "Cake",
//     "Rat",
//     "Tank",
//     "Blind",
//     "Spirit",
//     "Cable",
//     "Swamp",
//     "Einstein",
//     "Hide",
//     "Crystal",
//     "Gear",
//     "Kiss",
//     "Pew",
//     "Powder",
//     "Turtle",
//     "Bacon",
//     "Sherlock",
//     "Squash",
//     "Book",
//     "Razor",
//     "Dressing",
//     "Brick",
//     "Brazil",
//     "Tear",
//     "Stable",
//     "Bikini",
//     "Pen",
//     "Roll",
//     "Christmas",
//     "Rubber",
//     "Bay",
//     "Mother",
//     "Kick",
//     "Fog",
//     "Radio",
//     "Crab",
//     "Cone",
//     "Skull",
//     "Wheelchair",
//     "Egg",
//     "Butter",
//     "Werewolf",
//     "Cherry",
//     "Patient",
//     "Dryer",
//     "Drawing",
//     "Boss",
//     "Fever",
//     "Banana",
//     "Polish",
//     "Knot",
//     "Paint",
//     "Storm",
//     "Goldilocks",
//     "Pillow",
//     "Chain",
//     "Moses",
//     "Saw",
//     "Brother",
//     "Rail",
//     "Rope",
//     "Street",
//     "Pad",
//     "Captain",
//     "Wish",
//     "Axe",
//     "Shorts",
//     "Popcorn",
//     "Castle",
//     "Second",
//     "Team",
//     "Oasis",
//     "Mess",
//     "Miss",
//     "Avalanche",
//     "Texas",
//     "Sun",
//     "Letter",
//     "Rust",
//     "Wing",
//     "Steel",
//     "Ear",
//     "Scroll",
//     "Bunk",
//     "Cane",
//     "Venus",
//     "Ladder",
//     "Purse",
//     "Sheet",
//     "Napoleon",
//     "Sugar",
//     "Director",
//     "Ace",
//     "Scratch",
//     "Bucket",
//     "Caesar",
//     "Disk",
//     "Beard",
//     "Bulb",
//     "Bench",
//     "Scarecrow",
//     "Igloo",
//     "Tuxedo",
//     "Earth",
//     "Ram",
//     "Sister",
//     "Bread",
//     "Record",
//     "Dash",
//     "Greenhouse",
//     "Drone",
//     "Steam",
//     "Biscuit",
//     "Rip",
//     "Notre Dame",
//     "Lip",
//     "Shampoo",
//     "Cheese",
//     "Sack",
//     "Mountie",
//     "Sumo",
//     "Sahara",
//     "Walrus",
//     "Dust",
//     "Hammer",
//     "Cloud",
//     "Spray",
//     "St.Patrick",
//     "Kilt",
//     "Monkey",
//     "Frog",
//     "Dentist",
//     "Rainbow",
//     "Whistle",
//     "Reindeer",
//     "Kitchen",
//     "Lemonade",
//     "Slipper",
//     "Floor",
//     "Valentine",
//     "Pepper",
//     "Road",
//     "Shed",
//     "Bowler",
//     "Milk",
//     "Wheel",
//     "Magazine",
//     "Brass",
//     "Tea",
//     "Helmet",
//     "Flag",
//     "Troll",
//     "Jail",
//     "Sticker",
//     "Puppet",
//     "Chalk",
//     "Bonsai",
//     "Sweat",
//     "Gangster",
//     "Butterfly",
//     "Story",
//     "Salad",
//     "Armor",
//     "Smoke",
//     "Cave",
//     "Quack",
//     "Break",
//     "Snake",
//     "Mill",
//     "Gymnast",
//     "Wonderland",
//     "Driver",
//     "Spurs",
//     "Zombie",
//     "Pig",
//     "Cleopatra",
//     "Toast",
//     "Penny",
//     "Ant",
//     "Volume",
//     "Lace",
//     "Battleship",
//     "Maracas",
//     "Meter",
//     "Sling",
//     "Delta",
//     "Step",
//     "Joan of Arc",
//     "Comet",
//     "Bath",
//     "Polo",
//     "Gum",
//     "Vampire",
//     "Ski",
//     "Pocket",
//     "Battle",
//     "Foam",
//     "Rodeo",
//     "Squirrel",
//     "Salt",
//     "Mummy",
//     "Blacksmith",
//     "Chip",
//     "Goat",
//     "Laundry",
//     "Bee",
//     "Tattoo",
//     "Russia",
//     "Tin",
//     "Map",
//     "Yellowstone",
//     "Silk",
//     "Hose",
//     "Sloth",
//     "Kung Fu",
//     "Clock",
//     "Bean",
//     "Lightning",
//     "Bowl",
//     "Guitar",
//     "Ranch",
//     "Pearl",
//     "Flat",
//     "Virus",
//     "Ice Age",
//     "Coffee",
//     "Marathon",
//     "Attic",
//     "Wedding",
//     "Columbus",
//     "Pop",
//     "Sherwood",
//     "Trick",
//     "Nylon",
//     "Locust",
//     "Pacific",
//     "Cuckoo",
//     "Tornado",
//     "Memory",
//     "Jockey",
//     "Minotaur",
//     "Big Bang",
//     "Page",
//     "Sphinx",
//     "Crusader",
//     "Volcano",
//     "Rifle",
//     "Boil",
//     "Hair",
//     "Bicycle",
//     "Jumper",
//     "Smoothie",
//     "Sleep",
//     "Pentagon",
//     "Groom",
//     "River",
//     "Farm",
//     "Judge",
//     "Viking",
//     "Easter",
//     "Mud",
//     "Parrot",
//     "Comb",
//     "Salsa",
//     "Eden",
//     "Army",
//     "Paddle",
//     "Saloon",
//     "Mona Lisa",
//     "Mile",
//     "Blizzard",
//     "Quarter",
//     "Jeweler",
//     "Hamburger",
//     "Glasses",
//     "Sail",
//     "Boxer",
//     "Rice",
//     "Mirror",
//     "Ink",
//     "Beer",
//     "Teepee",
//     "Makeup",
//     "Microwave",
//     "Hercules",
//     "Sign",
//     "Pizza",
//     "Wool",
//     "Homer",
//     "Minute",
//     "Sword",
//     "Soup",
//     "Alaska",
//     "Baby",
//     "Potter",
//     "Shower",
//     "Blade",
//     "Noah",
//     "Soap",
//     "Tunnel",
//     "Peach",
//     "Dollar",
//     "Tip",
//     "Love",
//     "Jellyfish",
//     "Stethoscope",
//     "Taste",
//     "Fuel",
//     "Mosquito",
//     "Wizard",
//     "Big Ben",
//     "Garden",
//     "Waitress",
//     "Shoot",
//     "Shell",
//     "Lumberjack",
//     "Medic",
//     "Dream",
//     "Blues",
//     "Earthquake",
//     "Pea",
//     "Parade",
//     "Sled",
//     "Smell",
//     "Computer",
//     "Cow",
//     "Peanut",
//     "Window",
//     "Mustard",
//     "Sand",
//     "Golf",
//     "Crow",
//     "Iceland",
//     "Apron",
//     "Violet",
//     "Door",
//     "Tiger",
//     "Joker",
//     "House",
//     "Collar",
//     "Hawaii",
//     "Dwarf",
//     "Pine",
//     "Magician",
//     "Frost",
//     "Curry",
//     "Bubble",
//     "Wood"
// ]