import { Randomizer } from "./Randomizer";
import { Emoji } from "./Emoji";


const codenamesList: string[] = [
    "Hollywood",
    "Well",
    "Foot",
    "New York",
    "Spring",
    "Court",
    "Tube",
    "Point",
    "Tablet",
    "Slip",
    "Date",
    "Drill",
    "Lemon",
    "Bell",
    "Screen",
    "Fair",
    "Torch",
    "State",
    "Match",
    "Iron",
    "Block",
    "France",
    "Australia",
    "Limousine",
    "Stream",
    "Glove",
    "Nurse",
    "Leprechaun",
    "Play",
    "Tooth",
    "Arm",
    "Bermuda",
    "Diamond",
    "Whale",
    "Comic",
    "Mammoth",
    "Green",
    "Pass",
    "Missile",
    "Paste",
    "Drop",
    "Phoenix",
    "Marble",
    "Staff",
    "Figure",
    "Park",
    "Centaur",
    "Shadow",
    "Fish",
    "Cotton",
    "Egypt",
    "Theater",
    "Scale",
    "Fall",
    "Track",
    "Force",
    "Dinosaur",
    "Bill",
    "Mine",
    "Turkey",
    "March",
    "Contract",
    "Bridge",
    "Robin",
    "Line",
    "Plate",
    "Band",
    "Fire",
    "Bank",
    "Boom",
    "Cat",
    "Shot",
    "Suit",
    "Chocolate",
    "Roulette",
    "Mercury",
    "Moon",
    "Net",
    "Lawyer",
    "Satellite",
    "Angel",
    "Spider",
    "Germany",
    "Fork",
    "Pitch",
    "King",
    "Crane",
    "Trip",
    "Dog",
    "Conductor",
    "Part",
    "Bugle",
    "Witch",
    "Ketchup",
    "Press",
    "Spine",
    "Worm",
    "Alps",
    "Bond",
    "Pan",
    "Beijing",
    "Racket",
    "Cross",
    "Seal",
    "Aztec",
    "Maple",
    "Parachute",
    "Hotel",
    "Berry",
    "Soldier",
    "Ray",
    "Post",
    "Greece",
    "Square",
    "Mass",
    "Bat",
    "Wave",
    "Car",
    "Smuggler",
    "England",
    "Crash",
    "Tail",
    "Card",
    "Horn",
    "Capital",
    "Fence",
    "Deck",
    "Buffalo",
    "Microscope",
    "Jet",
    "Duck",
    "Ring",
    "Train",
    "Field",
    "Gold",
    "Tick",
    "Check",
    "Queen",
    "Strike",
    "Kangaroo",
    "Spike",
    "Scientist",
    "Engine",
    "Shakespeare",
    "Wind",
    "Kid",
    "Embassy",
    "Robot",
    "Note",
    "Ground",
    "Draft",
    "Ham",
    "War",
    "Mouse",
    "Center",
    "Chick",
    "China",
    "Bolt",
    "Spot",
    "Piano",
    "Pupil",
    "Plot",
    "Lion",
    "Police",
    "Head",
    "Litter",
    "Concert",
    "Mug",
    "Vacuum",
    "Atlantis",
    "Straw",
    "Switch",
    "Skyscraper",
    "Laser",
    "Scuba Diver",
    "Africa",
    "Plastic",
    "Dwarf",
    "Lap",
    "Life",
    "Honey",
    "Horseshoe",
    "Unicorn",
    "Spy",
    "Pants",
    "Wall",
    "Paper",
    "Sound",
    "Ice",
    "Tag",
    "Web",
    "Fan",
    "Orange",
    "Temple",
    "Canada",
    "Scorpion",
    "Undertaker",
    "Mail",
    "Europe",
    "Soul",
    "Apple",
    "Pole",
    "Tap",
    "Mouth",
    "Ambulance",
    "Dress",
    "Ice Cream",
    "Rabbit",
    "Buck",
    "Agent",
    "Sock",
    "Nut",
    "Boot",
    "Ghost",
    "Oil",
    "Superhero",
    "Code",
    "Kiwi",
    "Hospital",
    "Saturn",
    "Film",
    "Button",
    "Snowman",
    "Helicopter",
    "Loch Ness",
    "Log",
    "Princess",
    "Time",
    "Cook",
    "Revolution",
    "Shoe",
    "Mole",
    "Spell",
    "Grass",
    "Washer",
    "Game",
    "Beat",
    "Hole",
    "Horse",
    "Pirate",
    "Link",
    "Dance",
    "Fly",
    "Pit",
    "Server",
    "School",
    "Lock",
    "Brush",
    "Pool",
    "Star",
    "Jam",
    "Organ",
    "Berlin",
    "Face",
    "Luck",
    "Amazon",
    "Cast",
    "Gas",
    "Club",
    "Sink",
    "Water",
    "Chair",
    "Shark",
    "Jupiter",
    "Copper",
    "Jack",
    "Platypus",
    "Stick",
    "Olive",
    "Grace",
    "Bear",
    "Glass",
    "Row",
    "Pistol",
    "London",
    "Rock",
    "Van",
    "Vet",
    "Beach",
    "Charge",
    "Port",
    "Disease",
    "Palm",
    "Moscow",
    "Pin",
    "Washington",
    "Pyramid",
    "Opera",
    "Casino",
    "Pilot",
    "String",
    "Night",
    "Chest",
    "Yard",
    "Teacher",
    "Pumpkin",
    "Thief",
    "Bark",
    "Bug",
    "Mint",
    "Cycle",
    "Telescope",
    "Calf",
    "Air",
    "Box",
    "Mount",
    "Thumb",
    "Antarctica",
    "Trunk",
    "Snow",
    "Penguin",
    "Root",
    "Bar",
    "File",
    "Hawk",
    "Battery",
    "Compound",
    "Slug",
    "Octopus",
    "Whip",
    "America",
    "Ivory",
    "Pound",
    "Sub",
    "Cliff",
    "Lab",
    "Eagle",
    "Genius",
    "Ship",
    "Dice",
    "Hood",
    "Heart",
    "Novel",
    "Pipe",
    "Himalayas",
    "Crown",
    "Round",
    "India",
    "Needle",
    "Shop",
    "Watch",
    "Lead",
    "Tie",
    "Table",
    "Cell",
    "Cover",
    "Czech",
    "Back",
    "Bomb",
    "Ruler",
    "Forest",
    "Bottle",
    "Space",
    "Hook",
    "Doctor",
    "Ball",
    "Bow",
    "Degree",
    "Rome",
    "Plane",
    "Giant",
    "Nail",
    "Dragon",
    "Stadium",
    "Flute",
    "Carrot",
    "Wake",
    "Fighter",
    "Model",
    "Tokyo",
    "Eye",
    "Mexico",
    "Hand",
    "Swing",
    "Key",
    "Alien",
    "Tower",
    "Poison",
    "Cricket",
    "Cold",
    "Knife",
    "Church",
    "Board",
    "Cloak",
    "Ninja",
    "Olympus",
    "Belt",
    "Light",
    "Death",
    "Stock",
    "Millionaire",
    "Day",
    "Knight",
    "Pie",
    "Bed",
    "Circle",
    "Rose",
    "Change",
    "Cap",
    "Triangle"
]
const incelsList: string[] = [
    /* Insults */
    "Cuck",
    "Roastie",
    "Manlet",
    /* Things */
    "Rope",
    "Cope",
    "Hope",
    "Blackpill",
    "Redpill",
    "Bluepill",
    "SuicideFuel",
    "Looksmatch",

    /* Reactions */
    "Kek",
    "JFL",
    /* People */
    "Tyrone",
    "Chad",
    "Stacy",
    "Chang",
    "Curry",
    "Incel",
    "Elliot Rodger",
    /* Facial features */
    "Canthal Tilt",
    "",
    /* Misc */
    "Mogged"


]

const undercoverList: string[] = [
    /* Words that I've added */
    "Cuckold",
    /* Words from the game */
    "Horse",
    "Sauna",
    "Hooker",
    "Stool",
    "Mouth",
    "Touchdown",
    "Snake",
    "Whiskey",
    "Pickle",
    "Hose",
    "Legend",
    "Blush",
    "Dick",
    "Cock",
    "Alcohol",
    "Sausage",
    "Pecker",
    "Straight",
    "Sore",
    "Toy",
    "Black",
    "White",
    "Period",
    "Couch",
    "Juice",
    "Bra",
    "Dame",
    "Chick",
    "Bitch",
    "Score",
    "Sheep",
    "Strap",
    "Mattress",
    "Train",
    "Bondage",
    "Wiener",
    "Penis",
    "Furry",
    "Joystick",
    "Apples",
    "Condom",
    "Bisexual",
    "Hole",
    "Secretary",
    "Roll",
    "Strip",
    "Freak",
    "Tramp",
    "Foreskin",
    "Wine",
    "Pee",
    "Experiment",
    "Johnson",
    "Banana",
    "Clam",
    "Blow",
    "Balloon",
    "Semen",
    "Regret",
    "Stripper",
    "Homerun",
    "Trim",
    "Bar",
    "Wood",
    "Paddle",
    "Cowgirl",
    "John",
    "Candle",
    "Cigarette",
    "Cigar",
    "Knob",
    "Sex",
    "Gang",
    "Stud",
    "Screw",
    "Trousers",
    "Safe",
    "Girl",
    "Package",
    "Grope",
    "Jewels",
    "Beach",
    "Chubby",
    "Beef",
    "Bender",
    "Shaft",
    "Peaches",
    "Swallow",
    "Flower",
    "Trunk",
    "Sack",
    "Job",
    "Onion",
    "Bowl",
    "Jerk",
    "Crap",
    "Bush",
    "Box",
    "Mushroom",
    "Shame",
    "Couple",
    "Sweat",
    "Strobe",
    "Tubesteak",
    "Rug",
    "Butt",
    "Nylon",
    "Lick",
    "Hotel",
    "Boy",
    "Boob",
    "Biscuits",
    "Fatty",
    "Share",
    "Slut",
    "Swimmers",
    "Pound",
    "Tuna",
    "Roach",
    "Brownie",
    "Nuts",
    "Blonde",
    "Horny",
    "Catcher",
    "Body",
    "Dominate",
    "Mole",
    "Shave",
    "Orgasm",
    "Taboo",
    "Roof",
    "Twig",
    "Red",
    "Lube",
    "Nude",
    "Eat",
    "Hooters",
    "Legs",
    "Behind",
    "Olive",
    "Brown",
    "Shower",
    "Oyster",
    "Taco",
    "Salad",
    "Udders",
    "Rave",
    "Inch",
    "Nipple",
    "Gay",
    "High",
    "Booze",
    "Beaver",
    "Pussy",
    "Ice",
    "Skank",
    "Melons",
    "Tail",
    "Rack",
    "Uranus",
    "Queer",
    "Lingerie",
    "Needle",
    "Escort",
    "Herb",
    "Bear",
    "Beans",
    "Log",
    "Hamster",
    "Skirt",
    "Gigolo",
    "Tap",
    "Pie",
    "Vasectomy",
    "Queen",
    "Group",
    "Necklace",
    "Commando",
    "Headlights",
    "Ashes",
    "Bacon",
    "Goose",
    "Pillows",
    "Smell",
    "Latex",
    "Tavern",
    "Smegma",
    "Vegas",
    "Queef",
    "Hot",
    "Navel",
    "Gag",
    "Headboard",
    "Bed",
    "Ass",
    "Caboose",
    "Carpet",
    "Smoke",
    "Cuffs",
    "Teabag",
    "Shot",
    "Vein",
    "Purple",
    "Gash",
    "Nail",
    "Hand",
    "Head",
    "Chaps",
    "Animal",
    "Koozie",
    "Fish",
    "Snatch",
    "Rookie",
    "Tease",
    "Snort",
    "Vibrator",
    "Pucker",
    "Film",
    "Mug",
    "Bang",
    "Hammer",
    "Grandma",
    "Grass",
    "Sniff",
    "Prick",
    "Tent",
    "Baked",
    "Video",
    "Pub",
    "G-Spot",
    "Movie",
    "Jazz",
    "Friction",
    "Eyes",
    "Drunk",
    "Softballs",
    "Kitty",
    "Tequila",
    "Bottom",
    "Vinyl",
    "Prostate",
    "Chains",
    "Motorboat",
    "Crabs",
    "French",
    "Hurl",
    "Cheek",
    "Solo",
    "Lizard",
    "Threesome",
    "Breast",
    "Virgin",
    "Prison",
    "Donkey",
    "Monkey",
    "Douche",
    "Freckles",
    "Bond",
    "Keg",
    "Spank",
    "Boxers",
    "Throat",
    "Pinch",
    "Vodka",
    "Pot",
    "Lips",
    "Mom",
    "Finger",
    "Fluff",
    "Bling",
    "Rectum",
    "Speed",
    "Missionary",
    "Tickle",
    "Sin",
    "Vomit",
    "Porn",
    "Cuddle",
    "Moist",
    "Manboobs",
    "Flash",
    "Dildo",
    "Cocktail",
    "Sperm",
    "Emission",
    "tie",
    "Diarrhea",
    "Wad",
    "Pork",
    "Bottle",
    "Mixer",
    "Crack",
    "Fist",
    "Club",
    "Cucumber",
    "Spoon",
    "Seed",
    "Tip",
    "Intern",
    "Wang",
    "Pole",
    "Champagne",
    "Milk",
    "Loose",
    "Fire",
    "Choke",
    "Noodle",
    "Spread",
    "Doggy",
    "Tit",
    "Beer",
    "Waste",
    "Poker",
    "Gerbil",
    "Member",
    "Bartender",
    "Fetish",
    "Bone",
    "Motel",
    "Squirt",
    "Lotion",
    "Tongue",
    "Flesh",
    "Watch",
    "Player",
    "Balls",
    "Meat",
    "Cream",
    "Fecal",
    "Rubber",
    "Kinky",
    "Stalker",
    "Bust",
    "Tool",
    "Skid",
    "Wax",
    "Pitcher",
    "Knees",
    "Martini",
    "Lobster",
    "Feather",
    "Booty",
    "Joint",
    "Steamy",
    "Mesh",
    "Top",
    "Facial",
    "Weed",
    "Pipe",
    "Cherry",
    "Lust",
    "Knockers",
    "Fantasy",
    "Hump",
    "Poop",
    "Stiff",
    "Nurse",
    "Torture",
    "Bong",
    "Wench",
    "Pink",
    "Gangbang",
    "Love",
    "Coyote",
    "Drill",
    "Acid",
    "Line",
    "Stiletto",
    "Turd",
    "Touch",
    "Daddy",
    "Wet",
    "Pimp",
    "Hell",
    "Liquor",
    "Burn",
    "Drag",
    "Cougar",
    "Briefs",
    "Stones",
    "Naked",
    "Orgy",
    "Chest",
    "Whip",
    "Pig",
    "Jugs",
    "Lighter",
    "Cannons",
    "Down",
    "Clap"
]

const duetList: string[] = [
    "Drum",
    "Bride",
    "Wagon",
    "University",
    "Hit",
    "Ash",
    "Bass",
    "Astronaut",
    "Doll",
    "Nerve",
    "Coach",
    "Beam",
    "Spoon",
    "Country",
    "Nose",
    "King Arthur",
    "Stamp",
    "Camp",
    "Brain",
    "Leaf",
    "Tutu",
    "Coast",
    "Lunch",
    "Thunder",
    "Potato",
    "Desk",
    "Onion",
    "Elephant",
    "Anchor",
    "Cowboy",
    "Flood",
    "Mohawk",
    "Santa",
    "Pitcher",
    "Barbecue",
    "Leather",
    "Skates",
    "Musketeer",
    "Snap",
    "Saddle",
    "Genie",
    "Mark",
    "Shoulder",
    "Governor",
    "Manicure",
    "Anthem",
    "Halloween",
    "Newton",
    "Balloon",
    "Fiddle",
    "Craft",
    "Glacier",
    "Cake",
    "Rat",
    "Tank",
    "Blind",
    "Spirit",
    "Cable",
    "Swamp",
    "Einstein",
    "Hide",
    "Crystal",
    "Gear",
    "Kiss",
    "Pew",
    "Powder",
    "Turtle",
    "Bacon",
    "Sherlock",
    "Squash",
    "Book",
    "Razor",
    "Dressing",
    "Brick",
    "Brazil",
    "Tear",
    "Stable",
    "Bikini",
    "Pen",
    "Roll",
    "Christmas",
    "Rubber",
    "Bay",
    "Mother",
    "Kick",
    "Fog",
    "Radio",
    "Crab",
    "Cone",
    "Skull",
    "Wheelchair",
    "Egg",
    "Butter",
    "Werewolf",
    "Cherry",
    "Patient",
    "Dryer",
    "Drawing",
    "Boss",
    "Fever",
    "Banana",
    "Polish",
    "Knot",
    "Paint",
    "Storm",
    "Goldilocks",
    "Pillow",
    "Chain",
    "Moses",
    "Saw",
    "Brother",
    "Rail",
    "Rope",
    "Street",
    "Pad",
    "Captain",
    "Wish",
    "Axe",
    "Shorts",
    "Popcorn",
    "Castle",
    "Second",
    "Team",
    "Oasis",
    "Mess",
    "Miss",
    "Avalanche",
    "Texas",
    "Sun",
    "Letter",
    "Rust",
    "Wing",
    "Steel",
    "Ear",
    "Scroll",
    "Bunk",
    "Cane",
    "Venus",
    "Ladder",
    "Purse",
    "Sheet",
    "Napoleon",
    "Sugar",
    "Director",
    "Ace",
    "Scratch",
    "Bucket",
    "Caesar",
    "Disk",
    "Beard",
    "Bulb",
    "Bench",
    "Scarecrow",
    "Igloo",
    "Tuxedo",
    "Earth",
    "Ram",
    "Sister",
    "Bread",
    "Record",
    "Dash",
    "Greenhouse",
    "Drone",
    "Steam",
    "Biscuit",
    "Rip",
    "Notre Dame",
    "Lip",
    "Shampoo",
    "Cheese",
    "Sack",
    "Mountie",
    "Sumo",
    "Sahara",
    "Walrus",
    "Dust",
    "Hammer",
    "Cloud",
    "Spray",
    "St.Patrick",
    "Kilt",
    "Monkey",
    "Frog",
    "Dentist",
    "Rainbow",
    "Whistle",
    "Reindeer",
    "Kitchen",
    "Lemonade",
    "Slipper",
    "Floor",
    "Valentine",
    "Pepper",
    "Road",
    "Shed",
    "Bowler",
    "Milk",
    "Wheel",
    "Magazine",
    "Brass",
    "Tea",
    "Helmet",
    "Flag",
    "Troll",
    "Jail",
    "Sticker",
    "Puppet",
    "Chalk",
    "Bonsai",
    "Sweat",
    "Gangster",
    "Butterfly",
    "Story",
    "Salad",
    "Armor",
    "Smoke",
    "Cave",
    "Quack",
    "Break",
    "Snake",
    "Mill",
    "Gymnast",
    "Wonderland",
    "Driver",
    "Spurs",
    "Zombie",
    "Pig",
    "Cleopatra",
    "Toast",
    "Penny",
    "Ant",
    "Volume",
    "Lace",
    "Battleship",
    "Maracas",
    "Meter",
    "Sling",
    "Delta",
    "Step",
    "Joan of Arc",
    "Comet",
    "Bath",
    "Polo",
    "Gum",
    "Vampire",
    "Ski",
    "Pocket",
    "Battle",
    "Foam",
    "Rodeo",
    "Squirrel",
    "Salt",
    "Mummy",
    "Blacksmith",
    "Chip",
    "Goat",
    "Laundry",
    "Bee",
    "Tattoo",
    "Russia",
    "Tin",
    "Map",
    "Yellowstone",
    "Silk",
    "Hose",
    "Sloth",
    "Kung Fu",
    "Clock",
    "Bean",
    "Lightning",
    "Bowl",
    "Guitar",
    "Ranch",
    "Pearl",
    "Flat",
    "Virus",
    "Ice Age",
    "Coffee",
    "Marathon",
    "Attic",
    "Wedding",
    "Columbus",
    "Pop",
    "Sherwood",
    "Trick",
    "Nylon",
    "Locust",
    "Pacific",
    "Cuckoo",
    "Tornado",
    "Memory",
    "Jockey",
    "Minotaur",
    "Big Bang",
    "Page",
    "Sphinx",
    "Crusader",
    "Volcano",
    "Rifle",
    "Boil",
    "Hair",
    "Bicycle",
    "Jumper",
    "Smoothie",
    "Sleep",
    "Pentagon",
    "Groom",
    "River",
    "Farm",
    "Judge",
    "Viking",
    "Easter",
    "Mud",
    "Parrot",
    "Comb",
    "Salsa",
    "Eden",
    "Army",
    "Paddle",
    "Saloon",
    "Mona Lisa",
    "Mile",
    "Blizzard",
    "Quarter",
    "Jeweler",
    "Hamburger",
    "Glasses",
    "Sail",
    "Boxer",
    "Rice",
    "Mirror",
    "Ink",
    "Beer",
    "Teepee",
    "Makeup",
    "Microwave",
    "Hercules",
    "Sign",
    "Pizza",
    "Wool",
    "Homer",
    "Minute",
    "Sword",
    "Soup",
    "Alaska",
    "Baby",
    "Potter",
    "Shower",
    "Blade",
    "Noah",
    "Soap",
    "Tunnel",
    "Peach",
    "Dollar",
    "Tip",
    "Love",
    "Jellyfish",
    "Stethoscope",
    "Taste",
    "Fuel",
    "Mosquito",
    "Wizard",
    "Big Ben",
    "Garden",
    "Waitress",
    "Shoot",
    "Shell",
    "Lumberjack",
    "Medic",
    "Dream",
    "Blues",
    "Earthquake",
    "Pea",
    "Parade",
    "Sled",
    "Smell",
    "Computer",
    "Cow",
    "Peanut",
    "Window",
    "Mustard",
    "Sand",
    "Golf",
    "Crow",
    "Iceland",
    "Apron",
    "Violet",
    "Door",
    "Tiger",
    "Joker",
    "House",
    "Collar",
    "Hawaii",
    "Dwarf",
    "Pine",
    "Magician",
    "Frost",
    "Curry",
    "Bubble",
    "Wood"
]

const paintingsList: string[] = [
    "https://www.brushwiz.com/images/top-100/top_100_paintings_mona_lisa_by_leonardo_da_vinci.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_starry_night_by_vincent_van_gogh.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_scream_by_edvard_munch.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_night_watch_by_rembrandt_m29.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_kiss_by_gustav_klimt.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_arnolfini_portrait_by_jan_van_eyck_v44.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_girl_with_a_pearl_earring_by_johannes_vermeer.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_impression,_sunrise_by_claude_monet.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_las_meninas_by_diego_velazquez_l36.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_creation_of_adam_by_michelangelo.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_luncheon_of_the_boating_party_by_pierre-auguste_renoir_x40.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_grand_odalisque_by_jean_auguste_dominique_ingres_f91.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_happy_accidents_of_the_swing_by_jean-honore_fragonard_s7.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_liberty_leading_the_people_by_eugene_delacroix.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_birth_of_venus_by_sandro_botticelli_v46.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_napoleon_crossing_the_alps_by_jacques-louis_david_i39.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_musicians_by_caravaggio.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_american_gothic_by_grant_wood_c92.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_sunday_afternoon_on_the_island_of_la_grande_jatte_by_georges_seurat_t11.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_sleeping_gypsy_by_henri_rousseau.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_triumph_of_galatea_by_raphael_h76.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_gleaners_by_jean-francois_millet.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_primavera_by_sandro_botticelli_c99.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_third_of_may_1808_by_francisco_goya_h39.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_charles_i_in_three_positions_by_anthony_van_dyck.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_wanderer_above_the_sea_of_fog_by_caspar_david_friedrich.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_olympia_by_edouard_manet.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_tower_of_babel_by_pieter_bruegel_the_elder_w1.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_view_of_toledo_by_el_greco_c24.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_a_cotton_office_in_new_orleans_by_edgar_degas_u56.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_bacchus_and_ariadne_by_titian_y83.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_sleepers_by_gustave_courbet.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_gross_clinic_by_thomas_eakins_n38.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_ninth_wave_by_ivan_aivazovsky_m94.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_last_supper_by_leonardo_da_vinci_e69.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_st._george_and_the_dragon_by_paolo_uccello_o25.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_mr_and_mrs_robert_andrews_by_thomas_gainsborough.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_pollice_verso_by_jean-leon_gerome_n88.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_pilgrimage_to_cythera_by_antoine_watteau_h25.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_large_bathers_by_paul_cezanne_j99.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_astronomer_by_johannes_vermeer_l73.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_wave_by_william-adolphe_bouguereau_o33.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_fall_of_the_damned_by_peter_paul_rubens_k14.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_a_bar_at_the_folies_bergere_by_edouard_manet.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_storm_on_the_sea_of_galilee_by_rembrandt_f63.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_laughing_cavalier_by_frans_hals_g38.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_paris_street_in_rainy_weather_by_gustave_caillebotte.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_foxes_by_franz_marc_y6.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_lady_with_the_ermine_by_leonardo_da_vinci.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_watson_and_the_shark_by_john_singleton_copley_s96.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_ladies_waldegrave_by_joshua_reynolds_o12.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_arrangement_in_grey_and_black_no_1_portrait_of_the_artists_mother_by_james_abbott_mcneill_whistler_c15.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_dance_at_the_moulin_de_la_galette_by_pierre_auguste_renoir.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_breezing_up_by_winslow_homer_w66.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_great_wave_off_kanagawa_by_katsushika_hokusai_q50.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_large_seated_nude_by_amedeo_modigliani.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_stag_night_at_sharkeys_by_george_bellows.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_night_cafe_by_vincent_van_gogh.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_avenue_in_the_rain_by_childe_hassam.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_annunciation_by_leonardo_da_vinci.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_ambassadors_by_hans_holbein_the_younger_n93.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_flaming_june_by_frederic_lord_leighton_i45.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_susanna_and_the_elders_by_artemisia_gentileschi_r8.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_composition_viii_by_wassily_kandinsky_k55.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_oath_of_horatii_by_jacques-louis_david_k39.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_a_friend_in_need_by_cassius_marcellus_coolidge.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_dante_and_virgil_in_hell_by_william-adolphe_bouguereau_f37.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_saturn_devouring_his_son_by_francisco_goya_a27.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_battle_of_issus_by_albrecht_altdorfer_e1.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_potato_eaters_by_vincent_van_gogh.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_birth_of_venus_by_alexandre_cabanel_r44.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_mars_and_venus_allegory_of_peace_by_louis-jean-francois_lagrenee_s96.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_red_balloon_by_paul_klee_g28.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_lady_of_shalott_by_john_william_waterhouse_v45.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_portrait_of_a_gentleman_skating_by_gilbert_stuart_d40.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_hay_wain_by_john_constable_z55.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_boat_trip_by_mary_cassatt_b96.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_sleeping_venus_by_titian_g21.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_adoration_of_the_magi_by_gentile_da_fabriano_c29.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_portrait_of_a_young_man_by_raphael_l5.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_boulevard_montmartre_spring_by_camille_pissarro_m76.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_wedding_at_cana_by_paolo_veronese_f69.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_anatomy_lesson_of_dr._nicolaes_tulp_by_rembrandt_o27.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_raft_of_the_medusa_by_theodore_gericault_i70.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_kiss_by_francesco_hayez_l46.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_bath_by_jean-leon_gerome_i47.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_fort_vimieux_by_joseph_mallord_william_turner_a45.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_japanese_bridge_by_claude_monet_s92.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_washington_crossing_the_delaware_by_emanuel_gottlieb_leutze_j38.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_garden_of_earthly_delights_-_central_panel_by_hieronymus_bosch_t34.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_supper_at_emmaus_by_caravaggio_k55.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_feast_of_the_rosary_by_albrecht_durer.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_hireling_shepherd_by_william_holman_hunt_v34.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_hunters_in_the_snow_by_pieter_bruegel_the_elder_k1.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_seed_of_areoi_by_paul_gauguin_z97.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_barge_haulers_on_the_volga_by_ilya_repin.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_odalisque_by_francois_boucher.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_cardsharps_by_caravaggio.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_pont_du_gard_by_hubert_robert.jpg" ,
    "https://www.brushwiz.com/images/top-100/top_100_paintings_the_luncheon_on_the_grass_by_edouard_manet_d60.jpg"
]

const francisList: string[] = [
    "Beauty","Bravery","Brilliance","Brutality","Calmness","Charity","Coldness","Compassion","Confidence","Contentment","Courage","Curiosity","Dedication","Determination","Ego","Elegance","Enthusiasm","Envy","Evil","Fear","Generosity","Goodness","Graciousness","Hatred","Honesty","Honor","Hope","Humility","Humor","Insanity","Integrity","Intelligence","Jealousy","Kindness","Loyalty","Maturity","Patience","Perseverance","Sanity","Selfcontrol","Sensitivity","Sophistication","Stupidity","Sympathy","Talent","Tolerance","Trust","Warmth","Weakness","Wisdom","Wit","Adoration","Amazement","Anger","Anxiety","Apprehension","Clarity","Delight","Despair","Disappointment","Disbelief","Excitement","Fascination","Friendship","Grief","Happiness","Hate","Helpfulness","Helplessness","Infatuation","Joy","Love","Misery","Pain","Pleasure","Power","Pride","Relaxation","Relief","Romance","Sadness","Satisfaction","Silliness","Sorrow","Strength","Surprise","Tiredness","Uncertainty","Wariness","Weariness","Worry","Ability","Adventure","Artistry","Awe","Belief","Chaos","Comfort","Communication","Consideration","Crime","Culture","Death","Deceit","Defeat","Democracy","Dexterity","Dictatorship","Disquiet","Disturbance","Dreams","Energy","Enhancement","Failure","Faith","Faithfulness","Faithlessness","Favoritism","Forgiveness","Fragility","Frailty","Freedom","Gossip","Grace","Hearsay","Homelessness","Hurt","Idea","Idiosyncrasy","Imagination","Impression","Improvement","Inflation","Information","Justice","Knowledge","Laughter","Law","Liberty","Life","Loss","Luck","Luxury","Memory","Mercy","Motivation","Movement","Need","Omen","Opinion","Opportunism","Opportunity","Parenthood","Patriotism","Peace","Peculiarity","Poverty","Principle","Reality","Redemption","Refreshment","Riches","Rumor","Service","Shock","Skill","Slavery","Sleep","Sparkle","Speculation","Speed","Strictness","Submission","Success","Thought","Thrill","Truth","Unemployment","Unreality","Victory","Wealth","Magician","Mystery","Thriller","Pottermore","Pensieve","Play","Voldemort","Series","Genre","Drama","Theme","Flashback","Alchemy","Wand","Broomstick","Centaur","Narnia","Novel","Basilisk","Werewolf","Muggles","Middle-Earth","Zelda","Rupert","Disney","Dickensian","Wicca","Beowulf","Beatles","California","Epidemic","Influenza","Measles","Hiv","Smallpox","Tuberculosis","General","Disease","Vaccination","Malaria","Vaccine","Pathogen","Sars","Cholera","Ebola","Typhus","Aids","Cancer","Virulence","Infection","Infect","Zoonosis","Africa","Flu","Outbreak","Infectious","Virus","Mexico","H5N1","Polio","Leprosy","Preparedness","Infections","Dengue","Tsunamis","Bioterrorism","Immunization","Inoculation","Filariasis","Rinderpest","Rotavirus","Contagion","Continents","Endemic","History","Domestication","Food","Nutrition","Rice","Nutrient","Beef","Meat","Provender","Victuals","Cooking","Seafood","Pabulum","Animal","Cereal","Drink","Cheese","Fat","Soup","Butter","Yogurt","Nourishment","Agriculture","Pasta","Feed","Fish","Sustenance","Meal","Milk","Ingredients","Chicken","Sushi","Hunger","Sugar","Maize","Wheat","Plant","Vegetarian","Substance","Protein","Vitamin","Dairy","Nutriment","Chyme","Bitter","Foodstuff","Comestible","Saltiness","Eatable","Salad","Commissariat","Victual","Aliment","Water","Edible","Produce","Fruit","Vegetable","Restaurant","Chocolate","Coconut","Halal","Bread","Viands","Alimentation","Foody","Eat","Bacteria","Fermentation","Kitchen","Nut","Supplies","Goods","Pizza","Omega","Lemon","Vegetables","Livestock","Hamburger","Meals","Drinks","Clothing","Foodstuffs","Tobacco","Crops","Curing","Salting","Vegan","Biodiversity","Petfood","Environmentalism","Evolution","Bacon","Sweetness","Supermarket","Breadless","Umami","Kashrut","Rancidity","Taste","Cuisine","Pork","Hygiene","Mineral","Ingestion","Organism","Cell","Sustainability","Kosher","Fungi","Mushroom","Pickled","Solid","Beverage","Manna","Provisions","Fare","Yolk","Yoghurt","Loaf","Leftovers","Content","Medium","Slop","Potable","Drinkable","Mouthfeel","Alimentary","Salt","Cultivar","Seed","Carbohydrate","Legume","Bean","Pea","Lentil","Oilseed","Sunflower","Flaxseed","Rapeseed","Foodie","Sesame","Cherries","Icescr","Apple","Foodservice","Cyanide","Excretion","Tomato","Pumpkin","Eggplant","Potato","Carrot","Repast","Onion","Spinach","Vitellus","Yoghourt","Micronutrient","Lettuce","Farming","Bamboo","Asparagus","Kombucha","Perishable","Broccoli","Forage","Fodder","Spirulina","Cabbage","Cauliflower","Sausage","Products","Muscle","Organ","Gardening","Coffee","Oatmeal","Egg","Bee","Honey","Nectar","Vegetarianism","Blood","Foods","Nutrify","Supply","Items","Medicines","Starvation","Breakfast","Eating","Spaghetti","Raw","Bulk","Consumption","Coevolution","Poultry","Lasagna","Industry","Brunch","Consuming","Bagel","Drinking","Shortage","Snack","Health","Fresh","Burger","Domestic","Farmers","Steak","Imported","Grain","Luncheon","Ecosystem","Quality","Essential","Fertility","Besides","Selling","Spread","Available","Treats","Safe","Adding","Product","Care","Diet","Cheap","Costs","Dinner","Bringing","Consumers","Unep","Bring","Well","Specialty","Cleaning","Especially","Sells","Supplement","Sweet","Keeping","Variety","Imports","Sour","Aid","Crop","Needs","Wine","Oil","China","Poor","Making","Make","Scarce","Export","Local","Croquette","Businesses","Natural","Supper","Processing","Consumed","Cornbread","Business","Tea","More","Affected","Provide","Gobbler","Foodtography","Mealy","Opportunivore","Mexican","Glucose","Europe","Fructose","Sucrose","Market","Famine","Jugging","Polyphage","Acid","Cookbook","Vinegar","Citrus","Lime","Veganism","Orange","Leftover","Goatmeat","Macaroni","Viand","Ions","Sodium","Ort","Potassium","Chow","Electrolyte","Kidney","Iodine","Herbalism","Thyroid","Sweetbread","Pot","Noodle","Agroecosystem","Broth","Lunch","Ham","Fee","Fridge","Caffeine","Judaism","Islam","Hinduism","Obesity","Glutamate","Quorn","Refrigerator","Salmon","Dunch","Mushrooms","Porridge","Gastronomy","Resturant","Fleshmeat","Fooder","Maida","Salmagundi","Meaty","Tryptophan","Habit","Jibarito","Tachyphagia","Omnivore","Celery","Burrito","Disaccharides","Morality","Garlic","Activism","Taco","Insalivation","Sucralose","Plate","Texture","Stevia","Oilman","Hominy","Steviol","Pigmeat","Freezer","Cornmeal","Knife","Chowder","Cheeseburger","Sandwich","Ciabatta","Veal","Pho","Flavor","Dine","Ravioli","Fork","Slaughter","Jambalaya","Rendering","Catfood","Polyphagous","Slaughterhouses","Brainfood","Chickenability","Parmo","Taquito","Chopsticks","Niblet","Tool","Nosh","Gazpacho","Grocerant","Pilaf","Pottery","Oven","Spoon"
];

const getRandomWord = () => {
    return Randomizer.elementFromArray(list);
}

const getRandomWords = (n:number) => {
    const result = Randomizer.elementsFromArray(list,n);
    console.log("resulting words",result);
    console.log("and random number",Randomizer.intInRangeInclusive(0,1000))
    return result;
}
let list:Array<any> = codenamesList;

const useUnderCoverList = () => list = undercoverList;
const useDuetList = () => list = duetList;
const useCodenamesList = () => list = codenamesList
const useEmojiList = () => list = Emoji.list;
const usePaintingsList = () => list = paintingsList;
const useFrancisList = () => list = francisList;
export const WordList = {
    useFrancisList,
    getRandomWords:getRandomWords,
    getRandomWord:getRandomWord,
    useCodenamesList:useCodenamesList,
    useDuetList:useDuetList,
    useEmojiList:useEmojiList,
    usePaintingsList:usePaintingsList,
    useUnderCoverList:useUnderCoverList
}